effect_descs = (
    ('Atom', 'Creates a representation of an atom around the target'),
    ('BlockMask', 'Temporarily masks a block as a different block'),
    ('BlockWave', 'Creates a wave of blocks at the target location'),
    ('Ender', 'Causes the "Ender" effect'),
    ('EnderBeam', 'Creates the enderbeam effects at the target'),
    ('Explosion', 'Causes an explosion effect'),
    ('Firework', 'Causes a firework explosion'),
    ('Flames', 'Causes the Mob Spawner flame effect'),
    ('Geyser', 'Creates a "geyser" of water or lava'),
    ('ItemSpray', 'Sprays temporary items around the target'),
    ('Lightning', 'Causes a fake lightning strike'),
    ('ParticleBox', 'Draws a box of particles around the target'),
    ('ParticleLine', 'Draws a line of particle effects to the target'),
    ('ParticleRing', 'Draws a ring of particles around the target'),
    ('ParticleSphere', 'Draws a sphere of particles around the target'),
    ('ParticleTornado', 'Draws a persistent "tornado" of particles at the target'),
    ('Particles', 'Creates particle effects around the target'),
    ('Skybox', 'Alters the targets skybox'),
    ('Smoke', 'Creates a puff of smoke'),
    ('SmokeSwirl', 'Creates a persistent "swirl" of smoke'),
    ('Sound', 'Plays a sound effect from a resource pack'),
    ('Spin', 'Causes the mob to spin'),
)
