mechanic_descs = {
    'a': (
        ('ActivateSpawner', 'Activates a MythicMobs spawner at the targeted location'),
        ('ArrowVolley', 'Fires a volley of arrows'),
        ('Aura', 'Used to create custom status effects (buffs/debuffs) that can be targeted onto entities'),
    ),
    'c': (
        ('CancelEvent', 'Cancel the Event that triggered the current skill-tree'),
        ('Cast', '"Casts" a meta-skill using various advanced options'),
        ('Chain', 'Chains a skill between multiple targets that are near each other.'),
        ('Command', 'Executes a command for each target'),
        ('Consume', 'Deals damage and restores health per target hit'),
    ),
    'd': (
        ('Damage', 'Damages the target for an amount'),
        ('DamageBase', 'Damages the target for a percent of the mobs damage stat'),
        ('DamagePercent', 'Damages the target for a percent of their health'),
        ('Decapitate', 'Drops a player head item based on target'),
        ('Delay', 'Delays execution of the current skill list'),
        ('Disguise', 'Changes the casters disguise'),
        ('DisguiseRemove', 'Remove the casters disguise'),
        ('Dismount', 'Makes the caster dismount whatever theyre riding'),
        ('Doppleganger', 'Copies the appearance of the target player'),
    ),
    'e': (
        ('EjectPassenger', 'Ejects anything riding the caster'),
        ('Equip', 'Causes the casting mob to equip an item'),
        ('Explosion', 'Causes an explosion'),
    ),
    'f': (
        ('Feed', 'Feeds the target player'),
        ('ForcePull', 'Teleports the target to the mob'),
    ),
    'g': (
        ('GiveCurrency', 'Give money to a player. Requires Vault and a currency plugin'),
        ('GlobalCooldown', 'Sets the casters Global Cooldown timer'),
        ('Glow', 'Makes the target glow'),
    ),
    'h': (
        ('Heal', 'Heals the target'),
        ('HealPercent', 'Heals the target for a percentage of its max-health'),
    ),
    'i': (
        ('Ignite', 'Sets the target on fire'),
    ),
    'j': (
        ('JSONMessage', 'Sends a JSON-format message to the target player(s)'),
        ('Jump', 'Causes the caster to jump'),
    ),
    'l': (
        ('Leap', 'Causes the caster to leap towards the target'),
        ('Lightning', 'Strikes lightning at the target'),
        ('Look', 'Causes the caster to look at the target'),
        ('Lunge', 'Causes the caster to lunge forward at the target'),
    ),
    'm': (
        ('Message', 'Sends a message to the target player(s)'),
        ('Missile', 'Fires a homing missile projectile'),
        ('ModifyGlobalScore', 'Modifies a global scoreboard value'),
        ('ModifyScore', 'Modifies the score of a dummy player'),
        ('ModifyTargetScore', 'Modifies a scoreboard value of the target'),
        ('Mount', 'Summons a mob for the caster and mounts it'),
        ('MountTarget', 'Mounts the target'),
    ),
    'o': (
        ('Orbital', 'Applies an aura that causes a projectile to orbit around the target'),
    ),
    'p': (
        ('Potion', 'Applies a potion effect to the target'),
        ('Prison', 'Imprisons the target inside a block'),
        ('Projectile', 'Fires a highly-customizable projectile towards the target'),
        ('Pull', 'Pulls the target towards the mob'),
        ('PushButton', 'Pushes a button at the target location'),
    ),
    'r': (
        ('Rally', 'Causes other nearby mobs to attack the target'),
        ('RandomMessage', 'Sends a random message to the target player'),
        ('RandomSkill', 'Executes a random skill from a list'),
        ('Remount', 'Remounts the mob the caster originally spawned riding, if it is still alive'),
        ('Remove', 'Removes the target mob'),
        ('RunAIGoalSelector', 'Change PathfinderAIGoals'),
        ('RunAITargetSelector', 'Change PathfinderTargetGoals'),
    ),
    's': (
        ('SendActionMessage', 'Sends an Actionbar Message to the target player'),
        ('SendTitleMessage', 'Sends a Title/Subtitle Message to the target player'),
        ('SetBlockType', 'Change block type at target location'),
        ('SetGliding', 'Makes the target glide if they have elytra'),
        ('SetGlobalScore', 'Sets a global scoreboard value'),
        ('SetLevel', 'Changes the casting mobs level'),
        ('SetMobScore', 'Sets a scoreboard value on the casting mob'),
        ('SetName', 'Changes the target entitys name'),
        ('SetOwner', 'Makes the target the owner of the casting mob'),
        ('SetScore', 'Sets the scoreboard value of a dummy player'),
        ('SetSpeed', 'Sets the target entitys speed attribute'),
        ('SetStance', 'Sets the stance of the target mob'),
        ('SetTargetScore', 'Sets the score of the target'),
        ('Shoot', 'Shoots a projectile-item at the target'),
        ('ShootFireball', 'Shoots a fireball at the target'),
        ('ShootPotion', 'Throws a potion at the target'),
        ('ShootSkull', 'Shoots a wither skull at the target'),
        ('Signal', 'Sends a signal to a mob'),
        ('Skill', 'Executes a meta-skill. The butter for your bread.'),
        ('Spring', 'Creates a temporary spring of liquid at the target'),
        ('Stun', 'Stuns the target entity'),
        ('SudoSkill', 'Makes the target execute a skill'),
        ('Suicide', 'Causes the caster to die'),
        ('Summon', 'Summons other mobs at the target'),
    ),
    't': (
        ('TagAdd', 'Adds a scoreboard tag to the target'),
        ('TagRemove', 'Removes a scoreboard tag from the target'),
        ('TakeCurrency', 'Take money from a player. Requires Vault and a currency plugin'),
        ('Teleport', 'Teleports to the target'),
        ('TeleportTo', 'Teleports the target to a specified location'),
        ('Threat', 'Modifies the mobs threat towards the target'),
        ('Throw', 'Throws the target entity'),
        ('ToggleLever', 'Toggles a lever at the target location'),
        ('Totem', 'Creates a static "totem" at a location that pulses other skills'),
    ),
    'v': (
        ('Velocity', 'Modifies the velocity of the target entity(s)'),
    ),
    'w': (
        ('Weather', 'Modifies the weather in the target world'),
    ),
}
